image: golang:1.13

variables:
  # Please edit to your GitLab project
  REPO_NAME: golang-2019-2-tests

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - homework

hw1:
    stage: homework
    script:
      - if [[ $(wc -l <1/99_hw/game/main.go) -le 30 ]]; then echo "skip hw1 - no lines in file" && exit 0; fi
      - if [[ -n $(gofmt -l ./1/99_hw/...) ]]; then echo "Необходимо отформтаировать код при помощи gofmt" && exit 1; fi
      - go test -v ./1/99_hw/...
      - echo "Домашка 1 пройдена! Пишите преподавателю"

hw2:
    stage: homework
    script:
      - if [[ $(wc -l <2/99_hw/signer/signer.go) -le 10 ]]; then echo "skip hw2 - no lines in file" && exit 0; fi
      - if [[ -n $(gofmt -l ./2/99_hw/signer/...) ]]; then echo "Необходимо отформтаировать код при помощи gofmt" && exit 1; fi
      - go test -v -race ./2/99_hw/...
      - echo "Домашка 2 пройдена! Пишите преподавателю"
      
# hw3:
#     stage: homework
#     script:
#       - if [[ $(wc -l <3/99_hw/coverage/server.go) -le 20 ]]; then echo "skip hw3 - no lines in file" && exit 0; fi
#       - if [[ -n $(gofmt -l ./3/99_hw/coverage/...) ]]; then echo "Необходимо отформтаировать код при помощи gofmt" && exit 1; fi
#       - x=$(go test -v -cover ./3/99_hw... | grep coverage) && if [[ "$x" != *"100.0%"* ]]; then echo "$x" && exit 1; fi
#       - echo "Домашка 3 пройдена! Пишите преподавателю"

# hw4:
#     stage: homework
#     script:
#       - if [[ $(wc -l <4/99_hw/taskbot/bot.go) -le 40 ]]; then echo "skip hw4 - no lines in file" && exit 0; fi
#       - if [[ -n $(gofmt -l ./4/99_hw/taskbot/...) ]]; then echo "Необходимо отформтаировать код при помощи gofmt" && exit 1; fi
#       - go test -v -race ./4/99_hw/...
#       - echo "Домашка 4 пройдена! Пишите преподавателю"